# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'poetry' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  # Pods for poetry
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'Reachability', '~> 3.2' 
  target 'poetryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'poetryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
